annotations:
  truecharts.org/category: Cloud
  truecharts.org/max_helm_version: "3.14"
  truecharts.org/min_helm_version: "3.11"
  truecharts.org/train: stable
apiVersion: v2
appVersion: 2024.09.02
dependencies:
  - name: common
    version: 23.0.10
    repository: oci://tccr.io/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Jupyter a web based IDE
home: https://truecharts.org/charts/stable/jupyter
icon: https://truecharts.org/img/hotlink-ok/chart-icons/jupyter.webp
keywords:
  - Jupyter
  - Notebook
  - Lab
kubeVersion: '>=1.24.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: jupyter
sources:
  - https://github.com/jupyter/docker-stacks
  - https://github.com/truecharts/charts/tree/master/charts/stable/jupyter
  - https://hub.docker.com/r/jupyter/all-spark-noteboo
  - https://hub.docker.com/r/jupyter/base-noteboo
  - https://hub.docker.com/r/jupyter/datascience-noteboo
  - https://hub.docker.com/r/jupyter/minimal-noteboo
  - https://hub.docker.com/r/jupyter/pyspark-noteboo
  - https://hub.docker.com/r/jupyter/r-noteboo
  - https://hub.docker.com/r/jupyter/scipy-noteboo
  - https://hub.docker.com/r/jupyter/tensorflow-noteboo
type: application
version: 10.0.1
